### ISSUE TITLE
[1.12.2][1.0.10]Unable to connect to dedicated server

### ISSUE THREAD

**Issue by BionicFoxx** [V0idWa1k3r/ExPetrum#15]
Okay, so I've tried for the last half-hour to get ExPetrum to work server side so a few friends and I could play together, but it keeps crashing upon initialization. Here is the crash report: 

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/1/18 3:46 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: v0id.exp.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
	at v0id.exp.item.ItemArmor.<init>(ItemArmor.java:34)
	at v0id.exp.registry.ExPItemsRegistry.registerItems(ExPItemsRegistry.java:73)
	at v0id.exp.handler.ExPHandlerRegistry.onItemsRegistry(ExPHandlerRegistry.java:34)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_ExPHandlerRegistry_onItemsRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:755)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2393586936 bytes (2282 MB) / 3221749760 bytes (3072 MB) up to 6084886528 bytes (5803 MB)
	JVM Flags: 3 total; -Xmx6G -Xms3G -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2745 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                                  | Signature                                |
	|:----- |:--------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft | 1.12.2       | minecraft.jar                           | None                                     |
	| UCH   | mcp       | 9.42         | minecraft.jar                           | None                                     |
	| UCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.4.2745-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge     | 14.23.4.2745 | forge-1.12.2-14.23.4.2745-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | exp       | 1.0.10       | ExPetrum-1.12.2-1.0.10.jar              | fed4a2156e996f7a020359ca4c406cdde4ddcefd |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

Does anyone know whats going on?

**Comment by V0idWa1k3r** [comment]
Yeah I couldn't test the mod on the server and my testers didn't bother so you are probably the first person trying to make this work on a server. So you probably will experience a bunch of issues. Just dump them all here and I'll be fixing them.

**Comment by BionicFoxx** [comment]
> Yeah I couldn't test the mod on the server and my testers didn't bother so you are probably the first person trying to make this work on a server. So you probably will experience a bunch of issues. Just dump them all here and I'll be fixing them.
> Edit: Here, try this release.

I tried it, and it seemed to work. That is until the server world type needed to be changed.

```
[13:53:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[13:53:09] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[13:53:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[13:53:09] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2745 for Minecraft 1.12.2 loading
[13:53:09] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_171, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_171
[13:53:10] [main/INFO] [FML]: Searching C:\Users\ron\Desktop\ExPetrum\.\mods for mods
[13:53:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:53:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:53:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:53:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:53:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:53:13] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[13:53:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:53:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:53:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:53:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:53:16] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[13:53:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting minecraft server version 1.12.2
[13:53:23] [Server thread/INFO] [FML]: MinecraftForge v14.23.4.2745 Initialized
[13:53:23] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[13:53:24] [Server thread/INFO] [FML]: Replaced 1036 ore ingredients
[13:53:24] [Server thread/INFO] [FML]: Searching C:\Users\ron\Desktop\ExPetrum\.\mods for mods
[13:53:25] [Server thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[13:53:25] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[13:53:26] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, exp] at CLIENT
[13:53:26] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, exp] at SERVER
[13:53:28] [Server thread/INFO] [ExPetrum]: Registered %s with meta %d with volume %s and weight %s
[13:53:28] [Server thread/INFO] [ExPetrum]: Registered %s with meta %d with volume %s and weight %s
[13:53:28] [Server thread/INFO] [ExPetrum]: Registered %s with meta %d with volume %s and weight %s
[13:53:28] [Server thread/INFO] [ExPetrum]: Registered %s with meta %d with volume %s and weight %s
[13:53:28] [Server thread/INFO] [ExPetrum]: Registered %s with meta %d with volume %s and weight %s
[13:53:28] [Server thread/INFO] [ExPetrum]: Registered %s with meta %d with volume %s and weight %s
[13:53:28] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[13:53:29] [Server thread/INFO] [FML]: Found 1329 ObjectHolder annotations
[13:53:29] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[13:53:29] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[13:53:29] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[13:53:29] [Server thread/INFO] [ExPetrum]: ExPetrum has detected normal minecraft environment. No debug features enabled.
[13:53:29] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[13:53:29] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: OUTDATED Target: 14.23.4.2747
[13:53:29] [Forge Version Check/INFO] [forge.VersionCheck]: [exp] Starting version check at https://raw.githubusercontent.com/V0idWa1k3r/ExPetrum/master/version.json
[13:53:32] [Forge Version Check/INFO] [forge.VersionCheck]: [exp] Found status: UP_TO_DATE Target: null
[13:53:36] [Server thread/INFO] [FML]: Applying holder lookups
[13:53:36] [Server thread/INFO] [FML]: Holder lookups applied
[13:53:36] [Server thread/INFO] [FML]: Applying holder lookups
[13:53:36] [Server thread/INFO] [FML]: Holder lookups applied
[13:53:37] [Server thread/INFO] [FML]: Applying holder lookups
[13:53:37] [Server thread/INFO] [FML]: Holder lookups applied
[13:53:37] [Server thread/INFO] [FML]: Applying holder lookups
[13:53:37] [Server thread/INFO] [FML]: Holder lookups applied
[13:53:37] [Server thread/INFO] [FML]: Injecting itemstacks
[13:53:37] [Server thread/INFO] [FML]: Itemstack injection complete
[13:53:37] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Loading properties
[13:53:37] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Default game type: SURVIVAL
[13:53:37] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Generating keypair
[13:53:37] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting Minecraft server on *:25565
[13:53:37] [Server thread/INFO] [net.minecraft.network.NetworkSystem]: Using default channel type
[13:53:38] [Server thread/INFO] [ExPetrum]: A fair warning.
[13:53:38] [Server thread/INFO] [ExPetrum]: Forge is about to spew a bunch of "Dangerous alternative prefix" warnings.
[13:53:38] [Server thread/INFO] [ExPetrum]: No, ExPetrum isn't broken.
[13:53:38] [Server thread/INFO] [ExPetrum]: It simply overrides vanilla recipes to a dummy implementation to effectively remove them from the game without triggering the advancement error spam.
[13:53:38] [Server thread/INFO] [ExPetrum]: Thanks for reading. Have a nice day.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `torch`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `crafting_table`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `chest`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `bone_meal_from_bone`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `string_to_wool`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `fishing_rod`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `bow`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `leather_helmet`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `leather_chestplate`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `leather_leggings`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `leather_boots`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `iron_block`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gold_block`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `flint_and_steel`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `iron_helmet`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `iron_chestplate`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `iron_leggings`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `iron_boots`, expected `exp`. This could be a intended override, but in most cases indicates a broken mod.
[13:53:38] [Server thread/INFO] [FML]: Applying holder lookups
[13:53:38] [Server thread/INFO] [FML]: Holder lookups applied
[13:53:38] [Server thread/INFO] [FML]: Injecting itemstacks
[13:53:38] [Server thread/INFO] [FML]: Itemstack injection complete
[13:53:39] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[13:53:39] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Preparing level "world"
[13:53:39] [Server thread/INFO] [FML]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@73a21374)
[13:53:40] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 488 advancements
[13:53:40] [Server thread/INFO] [ExPetrum]: The world initialized without ExPetrum world type! Have you forgot to set it in advanced world settings?
[13:53:41] [Server thread/INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@73a21374)
[13:53:41] [Server thread/INFO] [ExPetrum]: The world initialized without ExPetrum world type! Have you forgot to set it in advanced world settings?
[13:53:41] [Server thread/INFO] [FML]: Loading dimension 1 (world) (net.minecraft.server.dedicated.DedicatedServer@73a21374)
[13:53:41] [Server thread/INFO] [ExPetrum]: The world initialized without ExPetrum world type! Have you forgot to set it in advanced world settings?
[13:53:41] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing start region for level 0
[13:53:42] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 4%
[13:53:43] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 7%
[13:53:44] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 10%
[13:53:45] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 14%
[13:53:46] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 18%
[13:53:47] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 24%
[13:53:48] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 28%
[13:53:49] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 34%
[13:53:50] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 41%
[13:53:51] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 45%
[13:53:52] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 50%
[13:53:54] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 56%
[13:53:55] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 62%
[13:53:56] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 69%
[13:53:57] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 76%
[13:53:58] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 84%
[13:53:59] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 91%
[13:54:00] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 99%
[13:54:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Done (21.086s)! For help, type "help" or "?"
[13:54:00] [Server thread/INFO] [FML]: Unloading dimension -1
[13:54:00] [Server thread/INFO] [FML]: Unloading dimension 1
```
Now, in server.properties, there is a field called "level-type", but the problem is, I don't know what to put there to get ExPetrum to default world gen. I tried "EXP", "exp", "EXPETRUM", and "ExPetrum"... Any ideas?

**Comment by V0idWa1k3r** [comment]
It should be expworld

**Comment by BionicFoxx** [comment]
>It should be expworld

Hey, thanks. Would you like a clean server copy?

**Comment by V0idWa1k3r** [comment]
I am able to join my own local server with ExP installed. Must be either a mod interaction issue or a setup issue. I'll help you fix that regardless.

**Comment by BionicFoxx** [comment]
So, I found out it is client side, and it has to do with interaction between client and server.

Here's the code (Since it was too long to post).

[latest.log](https://github.com/V0idWa1k3r/ExPetrum/files/2254954/latest.log)

**Comment by V0idWa1k3r** [comment]
Looks like entity data manager is getting corrupt for some reason which pretty much crashes the entirety of the network. I'll try to find out what causes that.

**Comment by BionicFoxx** [comment]
Mkay, next issue: 
```
[17:41:18] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.func_180186_a(Lnet/minecraft/util/math/Vec3i;)J
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.func_180186_a(Lnet/minecraft/util/math/Vec3i;)J
	at v0id.exp.block.plant.BlockCoralPlant.getExtendedState(BlockCoralPlant.java:135) ~[BlockCoralPlant.class:?]
	at v0id.exp.block.plant.BlockCoralPlant.func_176221_a(BlockCoralPlant.java:143) ~[BlockCoralPlant.class:?]
	at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:204) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:243) ~[ForgeHooks.class:?]
	at net.minecraft.block.Block.func_180647_a(Block.java:559) ~[aow.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:408) ~[awu$a.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:201) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:691) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[17:41:19] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[17:41:36] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Psyghlent lost connection: Disconnected
```

Error executing task, any ideas whats causing task errors?

**Comment by BionicFoxx** [comment]
Haha, coding is always fun, next problem.

```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 8/3/18 2:21 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.World.func_72894_k(F)V
	at v0id.exp.world.ExPWorld.onTick(ExPWorld.java:272)
	at v0id.exp.handler.ExPHandlerServer.onWorldTick(ExPHandlerServer.java:431)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_36_ExPHandlerServer_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2329089328 bytes (2221 MB) / 3164078080 bytes (3017 MB) up to 6084886528 bytes (5803 MB)
	JVM Flags: 3 total; -Xmx6G -Xms3G -Xmn1G
	IntCache: cache: 11, tcache: 75, allocated: 1, tallocated: 23
	FML: MCP 9.42 Powered by Forge 14.23.4.2745 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version      | Source                                  | Signature                                |
	|:--------- |:--------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft | 1.12.2       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp       | 9.42         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML       | 8.0.99.99    | forge-1.12.2-14.23.4.2745-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge     | 14.23.4.2745 | forge-1.12.2-14.23.4.2745-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | exp       | 1.0.10       | ExPetrum-1.12.2-1.0.11-build37.jar      | fed4a2156e996f7a020359ca4c406cdde4ddcefd |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

To sum it up, world tick is causing issues, it'll crash every 2 minutes.

**Comment by V0idWa1k3r** [comment]
Fixed in [this](https://github.com/V0idWa1k3r/ExPetrum/releases/tag/1.0.11-b38) build.
You are helping enough by providing the crash reports and being generally helpful with your logs and debugging. I honestly wouldn't ask more from a user.

**Comment by V0idWa1k3r** [comment]
Thanks to your server I've fixed most of the multiplayer issues. Feel free to open new issues as they are discovered.
